### ISSUE TITLE
Crashes on launch on KDE X11

### ISSUE THREAD

**Issue by Mitsunee** [flathub/org.blackfennec.app#6]
Wanted to try this application and it immediatly crashes.

<details>
<summary>Tracebacks of Errors</summary>

```
flatpak run org.blackfennec.app 

(process:3): Gtk-WARNING **: 19:58:44.449: Locale not supported by C library.
        Using the fallback 'C' locale.
libEGL warning: DRI2: could not open /dev/dri/card1 (No such file or directory)
amdgpu: drmGetDevice2 failed.
libGL error: glx: failed to create dri3 screen
libGL error: failed to load driver: radeonsi
libGL error: failed to open /dev/dri/card1: No such file or directory
libGL error: failed to load driver: radeonsi
WARNING:blackfennec.layers.overlay.overlay_factory_visitor:An unknown exception has been ignored:
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/blackfennec/layers/overlay/overlay_factory_visitor.py", line 28, in visit_reference
    target = subject_reference.resolve()
  File "/app/lib/python3.10/site-packages/blackfennec/structure/reference.py", line 49, in resolve
    current_structure = navigator.navigate(current_structure)
  File "/app/lib/python3.10/site-packages/blackfennec/structure/reference_navigation/uri_navigator.py", line 27, in navigate
    return document.content
  File "/app/lib/python3.10/site-packages/blackfennec/document_system/document.py", line 81, in content
    self._load_content()
  File "/app/lib/python3.10/site-packages/blackfennec/document_system/document.py", line 92, in _load_content
    with self.resource_type.load_resource(self, "r") as raw:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/app/lib/python3.10/site-packages/blackfennec/document_system/resource_type/protocols/bftype_resource_type.py", line 38, in load_resource
    raise KeyError(f'Could not find type with name: {type_name}')
KeyError: 'Could not find type with name: Map'

ERROR:blackfennec.extension.extension:Failed to create extension base from module <module 'base' from '/app/lib/python3.10/site-packages/base/__init__.py'>
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/blackfennec/extension/extension.py", line 102, in load
    module.create_extension(extension_api)
  File "/app/lib/python3.10/site-packages/base/__init__.py", line 47, in create_extension
    for type, factory in zip(_types(extension_api), factories):
  File "/app/lib/python3.10/site-packages/base/__init__.py", line 24, in _types
    api.type_loader.load(BASE_NAME + '/file/file.json'),
  File "/app/lib/python3.10/site-packages/blackfennec/type_system/type_loader.py", line 20, in load
    type = TypeParser.parse(structure)
  File "/app/lib/python3.10/site-packages/blackfennec/type_system/type_parser.py", line 45, in parse
    structure = cls._merge_super(structure)
  File "/app/lib/python3.10/site-packages/blackfennec/type_system/type_parser.py", line 35, in _merge_super
    return layer.apply(underlay=super, overlay=structure)
  File "/app/lib/python3.10/site-packages/blackfennec/layers/merge/merged_layer.py", line 14, in apply
    encaps = merger.merge(underlay)
  File "/app/lib/python3.10/site-packages/blackfennec/layers/merge/merger.py", line 56, in merge
    return underlay.accept(self)
  File "/app/lib/python3.10/site-packages/blackfennec/structure/reference.py", line 57, in accept
    return visitor.visit_reference(self)
  File "/app/lib/python3.10/site-packages/blackfennec/structure/visitor.py", line 26, in visit_reference
    return self.visit_structure(subject)
  File "/app/lib/python3.10/site-packages/blackfennec/layers/merge/merger.py", line 59, in visit_structure
    raise TypeError("cannot merge structures of different types")
TypeError: cannot merge structures of different types
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/lib/python3.10/site-packages/blackfennec/__main__.py", line 81, in <module>
    main()
  File "/app/lib/python3.10/site-packages/blackfennec/__main__.py", line 76, in main
    initialisation_service = InitialisationService(extension_configuration_file=EXTENSIONS)
  File "/app/lib/python3.10/site-packages/blackfennec/util/initialisation_service.py", line 78, in __init__
    self._setup_extensions(extension_configuration_file)
  File "/app/lib/python3.10/site-packages/blackfennec/util/initialisation_service.py", line 110, in _setup_extensions
    extension_initialisation_service.load_extensions_from_file(
  File "/app/lib/python3.10/site-packages/blackfennec/extension/extension_initialisation_service.py", line 90, in load_extensions_from_file
    extension_source.load_extensions(extension_api)
  File "/app/lib/python3.10/site-packages/blackfennec/extension/extension_source.py", line 133, in load_extensions
    extension.load(extension_api)
  File "/app/lib/python3.10/site-packages/blackfennec/extension/extension.py", line 110, in load
    raise exception
  File "/app/lib/python3.10/site-packages/blackfennec/extension/extension.py", line 102, in load
    module.create_extension(extension_api)
  File "/app/lib/python3.10/site-packages/base/__init__.py", line 47, in create_extension
    for type, factory in zip(_types(extension_api), factories):
  File "/app/lib/python3.10/site-packages/base/__init__.py", line 24, in _types
    api.type_loader.load(BASE_NAME + '/file/file.json'),
  File "/app/lib/python3.10/site-packages/blackfennec/type_system/type_loader.py", line 20, in load
    type = TypeParser.parse(structure)
  File "/app/lib/python3.10/site-packages/blackfennec/type_system/type_parser.py", line 45, in parse
    structure = cls._merge_super(structure)
  File "/app/lib/python3.10/site-packages/blackfennec/type_system/type_parser.py", line 35, in _merge_super
    return layer.apply(underlay=super, overlay=structure)
  File "/app/lib/python3.10/site-packages/blackfennec/layers/merge/merged_layer.py", line 14, in apply
    encaps = merger.merge(underlay)
  File "/app/lib/python3.10/site-packages/blackfennec/layers/merge/merger.py", line 56, in merge
    return underlay.accept(self)
  File "/app/lib/python3.10/site-packages/blackfennec/structure/reference.py", line 57, in accept
    return visitor.visit_reference(self)
  File "/app/lib/python3.10/site-packages/blackfennec/structure/visitor.py", line 26, in visit_reference
    return self.visit_structure(subject)
  File "/app/lib/python3.10/site-packages/blackfennec/layers/merge/merger.py", line 59, in visit_structure
    raise TypeError("cannot merge structures of different types")
TypeError: cannot merge structures of different types
``` 

</details>

**Comment by AndreasVerden** [comment]
Hi, thanks for submitting an issue!
We are just about to release version 0.11 which should fix this issue :)
Your feedback would be much appreciated!

Are you running on ARM?

**Comment by Mitsunee** [comment]
> Hi, thanks for submitting an issue! We are just about to release version 0.11 which should fix this issue :) Your feedback would be much appreciated!

Just tried to install again and 0.11.0 launches perfectly. App seems to work, just couldn't find a way to set dark mode, not sure why flatpak apps launch in light theme for me, might be user error.
 
> Are you running on ARM?

I'm on x86_64. Guess I could've included my specs above, my bad:

Distro: Fedora Linux 36  
CPU: Ryzen 5 5600X (12)   
RAM: 15914MiB   
GPU: AMD Radeon RX 6600 XT

Also closing this issue as you solved it 👍🏻
